### ISSUE TITLE
The counter goes to 18 numbers.

### ISSUE THREAD

**Issue by gr1ndslvt** [vassdeniss/pizzaclicker#1]
The counter for the pizzas goes up to 18 numbers at a time. But thankfully this can be only done using a autoclicker software. So the possibility is of this happening is rare. But it needs to be fixed.

**Comment by vassdeniss** [comment]
Will look into it!

**Comment by vassdeniss** [comment]
Fixed it in v1.1 @happymac1987

**Comment by vassdeniss** [comment]
Fixed in v1.1 @happymac1987
